// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oekcvzhbtdtzqjprhpxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9la2N2emhidGR0enFqcHJocHh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4ODU5MTAsImV4cCI6MjA3MjQ2MTkxMH0.MVUklGxsJx944LLFKwZhXfq1UFu_h-YDCij5gQM_67E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});